---
- name: Install Apache Guacamole 1.5.5
  hosts: smb
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - build-essential
          - libcairo2-dev
          - libjpeg-turbo8-dev
          - libpng-dev
          - libtool-bin
          - libossp-uuid-dev
          - libavcodec-dev
          - libavformat-dev
          - libswscale-dev
          - freerdp2-dev
          - libpango1.0-dev
          - libssh2-1-dev
          - libvncserver-dev
          - libpulse-dev
          - libssl-dev
          - libvorbis-dev
          - libwebp-dev
          - tomcat9
          - tomcat9-admin
          - tomcat9-user
          - openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Download Apache Guacamole
      get_url:
        url: https://downloads.apache.org/guacamole/1.5.5/source/guacamole-server-1.5.5.tar.gz
        dest: /tmp/guacamole-server-1.5.5.tar.gz

    - name: Extract the source code
      unarchive:
        src: /tmp/guacamole-server-1.5.5.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Compile and build Guacamole
      shell: |
        cd /tmp/guacamole-server-1.5.5
        ./configure --with-init-dir=/etc/init.d
        make
        make install
        ldconfig

    - name: Create Guacamole configuration directory
      file:
        path: /etc/guacamole
        state: directory

    - name: Configure guacd as a service
      service:
        name: guacd
        state: started
        enabled: yes

    - name: Download Guacamole WAR file
      get_url:
        url: https://downloads.apache.org/guacamole/1.5.5/binary/guacamole-1.5.5.war
        dest: /var/lib/tomcat9/webapps/guacamole.war
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
