---
- name: Configure Samba to share a folder
  hosts: smb
  become: true
  tasks:
    - name: Install Samba
      apt:
        name: samba
        state: present
      when: ansible_os_family == "Debian"

    - name: Create shared folder
      file:
        path: /srv/smb/shared
        state: directory
        mode: '0777'

    - name: Configure Samba
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [Shared]
          path = /srv/smb/shared
          browseable = yes
          read only = no
          guest ok = yes
        marker: "# ANSIBLE CONFIG SMB"

    - name: Restart Samba service
      service:
        name: smbd
        state: restarted

    - name: Ensure Samba service is running
      service:
        name: smbd
        state: started
        enabled: true
